### ISSUE TITLE
Add project file

### ISSUE THREAD

**Issue by peterfriese** [mateusnevoli/app-code#1]
This project is missing the main project file (usually `aplicativo.xcproject`). Also, you might want to check in the `aplicativo.xcworkspace` file/folder (instead of zipping it).

Unless I've got the project file, I won't be able to open ' compile the project.

**Comment by mateusnevoli** [comment]
I added it. But I wasn't able to add both .xcproject and .wcworkspace without zipping it (it did it automatically). If you can't get access them, I created this google drive link (https://drive.google.com/drive/folders/1TMNOkVPTYHxEiiQBX_kTny1FXkZe99Dk?usp=sharing )or you can give me an email and I send you.

**Comment by peterfriese** [comment]
Hmmm... can you tell me how you checked in the project? This sounds team odd.

**Comment by mateusnevoli** [comment]
You mean how I added the project in the repo? I just dragged it to the demarcated area

**Comment by mateusnevoli** [comment]
But did you get access to the project?

**Comment by peterfriese** [comment]
Ok, so it seems like you added the files in this project by drag'n'drop to this repo. 

Actually, I am a bit surprised GitHub supports this, as this makes things a lot more complicated (see for example the zipped project and workspace files).

To answer your question - I was not able to open the project. I would recommend reading up on how to check in source code files to GitHub using Xcode or the command line. Drag'n'drop isn't a scalable solution when collaborating on a project.

**Comment by mateusnevoli** [comment]
Hello Peter, sorry for the inconvenience

Now, I think I made it (at least it worked flawlessly with me after I cloned it) Its in a new repo called "app--"

**Comment by peterfriese** [comment]
Hi Mateus, I was able to clone the repo and open the project.
